version: "3.9"
services:
  ab-testing:
    build: .
    ports:
      - "80:8030"
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - DATABASE_USER=kong
      - DATABASE_PASSWORD=kong
      - DATABASE_NAME=ab_testing
      - SERVER_PORT=80
  # postgres:
  #   image: postgres:alpine
  #   restart: always
  #   environment:
  #     POSTGRES_USER: guest
  #     POSTGRES_PASSWORD: guest
  #     POSTGRES_DB: speakeasy
  #   ports:
  #     - "5432:5432"
